# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ZXBasic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.11

    - name: Caches pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-py3.8.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.1.14
        poetry config virtualenvs.in-project true

    - name: Set up poetry cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-python3.8-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: poetry install

    - name: Lint code
      run: poetry run poe lint

    - name: Run tests
      run: poetry run poe test
