# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ZXBasic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PYTHON_VERSION: 3.10.8

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Caches pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-py-${{ env.PYTHON_VERSION }}

    - name: Install poetry
      run: |
        pip install -U pip~=22.1
        pip install poetry~=1.1.14
        poetry config virtualenvs.in-project true

    - name: Set up poetry cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-py-${{ env.PYTHON_VERSION }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: poetry install --verbose

    - name: Lint code
      run: poetry run poe lint

    - name: Run tests
      run: poetry run poe test
